# ~/.bashrc: executed by bash(1) for non-login shells.

#********************************************************************
# ********************* ALEX HAHN'S BASH_PROFILE ********************
# *******************************************************************

# -------------------------------------------------------------------
#
# Description: This file holds my BASH configurations and aliases
# Sections:
# 1.    Prompt Configuration
# 2.    Aliases and Remappings (remapping defaults and adding functionality
# 3.    File and Folder Management
# 4.    Searching
# 5.    Process Management
# 6.    Networking
# 7.    System Operations & Information
# 8.    Web Development
# 9.    Reminders & Notes

# -------------------------------------------------------------------

#   ------------------------------
#   1. Prompt Configuration
#   ------------------------------

# Colors (wrap around command (char))
# #\[\e[1;30m\]\char\[\e[0;39m\] -- Grey text
# #\[\e[1;31m\]\char\[\e[0;39m\] -- Red Text
# #\[\e[1;32m\]\char[\e[0;39m\] -- Green
# #\[\e[1;33m\]\char\[\e[0;39m\] -- Yellow
# #\[\e[1;34m\]\char\[\e[0;39m\] -- Dark Blue
# #\[\e[1;35m\]\char\[\e[0;39m\] -- Magenta
# #\[\e[1;36m\]\char\[\e[0;39m\] -- Bright Blue
# #\[\e[1;37m\]\char\[\e[0;39m\] -- White
# # Backround colors are the same but are in the 40's ie "\e[32;40m\]" is Green
# # text with a Black background

# Data for prompt (choose)
# \h -- (short) Hostname (H for long)
# \u -- Username
# \w -- Path (to current working dir from home (~))
#\d -- Date in "Wed Jun 10" format
# \j -- The number of processes you've suspended in this shell by hitting ^Z
# \l -- Name of the shell's terminal device (note if using cygwin probably
# pty because it is a "psuedo Terminal" for text terminal (tty
# "TeleTYpe terminal"))
# \s -- Name of the shell executable
# \@ -- Date in 12 hr format with am/pm
# \! -- Current command's position in the history buffer
# \# -- Command number (this will count up at each prompt)
# \$ If wou are not root, inserts a "$"; if you are at root,
# you get a  "#"

#-------------
# MY PROMPT
#-------------

# In the end it's easiest if I use this functional prompt that changes color
# depending on git and svn configs. Custom file
source ~/prompt.sh

export PS1="\n\[\e[37;1m\]\u@\h\[\e[35;1m\] Shell: \s \l \[\e[31;1m\]\d \@\[\e[37;1m\] This is command \#\n\[\e[32;1m\]\w\[\e[36;1m\] => \[\e[0m\]"
export PS2="| => "

# A little more in depth prompt
#export PS1="\n\[\e[33;1m\]\u@\H\[\e[35;1m\] Shell:\s\l \[\e[31;1m\]\d \@\[\e[37;1m\] This is command\#\n\[\e[32;1m\]\w\[\e[36;1m\] => \[\e[0m\]"
#export PS2="| => "

#Old Prompt, pretty wild
#export PS1="\n✌️ 🌇 🐣 🎉 💻 🛀 💊  💉 🗽 💰 💵 💸 🇩🇪 🔬 🔭 🏦 🗾 🇯🇵 🎵 ⚽️🎣🍺 👍 🍻 🍸 🍹 🍷 🍴  🌅 🚀 🇺🇸\n\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\d, \@\n✌︎⚽︎ \u⚛∰ \n\w\nThis is the \#th command\nTurn ⇮↑⇫⇑⥉⟰ ⬆︎ ☝︎ ⥣ ⤊ ⤉⇧↥⇭⇯\nYou're doing great! Amazing! λ: "

#   ------------------------------
#   2.Aliases and Remappings
#   ------------------------------
# Very useful general aliases
alias open='cygstart'
alias clear='printf "\033c"'

# ls aliases
#alias ls='ls --color=auto'  #ls has colors (TODO: google how to set), bash
alias ll='ls -l'            #ll is list long format
alias la='ls -a'            #la is list everything (hidden too)
alias lt='ls -lt'           #lt is list in long format in order
alias lla='ls -la'          #lla is list everything long format
alias lat='ls -lat'         #lat is list everything in long format in order

# wc aliases
alias wcl='wc -l' #wcl is line count
alias wcw='wc -w' #wcw is word count
alias wcc='wc -m' #wcc is character count
alias wcb='wc -c' #wcb is byte count

# find aliases
alias findfile='find . -name' # recursive search by name

# grep aliases
alias grep='grep --color=auto' #grep should just always have color
export GREP_COLOR='1;33' #Set the regex match color
alias grepn='grep -n'    #Displays the line number
alias grepc='grep -c'    #Give count of matched LINES (not words)
alias grepr='grep -r'    #Recursive grep (all files, all dirs under .)
alias grepi='grep -i'    #grepi is case insensitive grep
alias grepv='grep -v'    #Inverr grep, useful for returning all

# Python script to make svn status output colorized
alias svn='~/svnColor.py'

#   ------------------------------
#   3. File and Directory Management
#   ------------------------------

export CLICOLOR=1
export LSCOLORS=Dxfxcxdxbxegedabagaced
#export LSCOLORS=ExFxBxDxCxegedabagacad



#
## If not running interactively, don't do anything
#case $- in
#    *i*) ;;
#      *) return;;
#esac
#
## don't put duplicate lines or lines starting with space in the history.
## See bash(1) for more options
#HISTCONTROL=ignoreboth
#
## append to the history file, don't overwrite it
#shopt -s histappend
#
## for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
#HISTSIZE=1000
#HISTFILESIZE=2000
#
## check the window size after each command and, if necessary,
## update the values of LINES and COLUMNS.
#shopt -s checkwinsize
#
## If set, the pattern "**" used in a pathname expansion context will
## match all files and zero or more directories and subdirectories.
##shopt -s globstar
#
## make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
#
## set variable identifying the chroot you work in (used in the prompt below)
#if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
#    debian_chroot=$(cat /etc/debian_chroot)
#fi
#
## set a fancy prompt (non-color, unless we know we "want" color)
#case "$TERM" in
#    xterm-color) color_prompt=yes;;
#esac
#
## uncomment for a colored prompt, if the terminal has the capability; turned
## off by default to not distract the user: the focus in a terminal window
## should be on the output of commands, not on the prompt
##force_color_prompt=yes
#
#if [ -n "$force_color_prompt" ]; then
#    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
#	# We have color support; assume it's compliant with Ecma-48
#	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
#	# a case would tend to support setf rather than setaf.)
#	color_prompt=yes
#    else
#	color_prompt=
#    fi
#fi
#
#if [ "$color_prompt" = yes ]; then
#    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
#else
#    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
#fi
#unset color_prompt force_color_prompt
#
## If this is an xterm set the title to user@host:dir
#case "$TERM" in
#xterm*|rxvt*)
#    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
#    ;;
#*)
#    ;;
#esac
#
## enable color support of ls and also add handy aliases
#if [ -x /usr/bin/dircolors ]; then
#    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
#    alias ls='ls --color=auto'
#    #alias dir='dir --color=auto'
#    #alias vdir='vdir --color=auto'
#
#    alias grep='grep --color=auto'
#    alias fgrep='fgrep --color=auto'
#    alias egrep='egrep --color=auto'
#fi
#
## some more ls aliases
#alias ll='ls -alF'
#alias la='ls -A'
#alias l='ls -CF'
#
## Add an "alert" alias for long running commands.  Use like so:
##   sleep 10; alert
#alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
#
## Alias definitions.
## You may want to put all your additions into a separate file like
## ~/.bash_aliases, instead of adding them here directly.
## See /usr/share/doc/bash-doc/examples in the bash-doc package.
#
#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases
#fi
#
## enable programmable completion features (you don't need to enable
## this, if it's already enabled in /etc/bash.bashrc and /etc/profile
## sources /etc/bash.bashrc).
#if ! shopt -oq posix; then
#  if [ -f /usr/share/bash-completion/bash_completion ]; then
#    . /usr/share/bash-completion/bash_completion
#  elif [ -f /etc/bash_completion ]; then
#    . /etc/bash_completion
#  fi
#fi
#
## OPAM configuration
#. /home/vagrant/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
#
## opam config
#eval `opam config env`
#alias ocaml=utop
#
#alias sublime=sublime-text-3
